### ISSUE TITLE
Current issues with 60fps

### ISSUE THREAD

**Issue by Superstarxalien** [CTR-tools/CTR-ModSDK#18]
### Semi-functional patches
* Particles are patched emitter-by-emitter, 231 emitters unpatched, should patch Particles_UpdateLists
* Texture scrolling (turbo, waterfall, etc) run at 30fps
* Bosses dont constantly spam weapons, but it's still not right
* When opening Adv Hub door with key, zoom out should take 2 sec, not 1 sec
* Blizzard Bluff + Sewer Speedway update hazards at 30fps
* N Gin Labs barrel hazard runs at 30fps
* Weapon roulette flashes too fast, but duration is correct
* Shiled weapon shakes too much
* Entering warp pad sometimes works right, and sometimes throws player upward
* Blinking map UI, partly fixed and partly abandoned
* AI animations
* Player reverse, crash, jump animation
* Spiders have a slightly-off cycle

## Known issues
* Steering angular acceleration isn't patched for 60fps (see Player_Steer_GetAngularVelocity)
* Animations are half-working, half-fix
* Flashing colors for player icons are too fast
* Demo Mode only lasts half-time (even though it "should" be fixed???)
* UI highlight (red/yellow) in menus is too fast
* Demo Mode / End-Of-Race cameras sometimes are too fast
* Adventure Garage camera is too fast
* Adventure Hub Warp pad electric field
* Lots of flashing text is flashing too fast
* At end of Time Trial / Relic, high scores disappear halfway off-screen
* AI acceleration from starting line
* Screen fade transitions (fade to black, fade to white, etc.)
* Red potion (fix disabled, freezes game)
* Bubble particles fail to be culled by water surface (hits the top of the screen)
* Still can't skip weapon roulette by pressing circle
* Wumpa gets collected too quickly (code for this is in DrawHUD_Racing)

**Comment by Superstarxalien** [comment]
Demo mode now works correctly as of edf0d83

**Comment by JohnBillington** [comment]
> Add another Known Issue:
> 
> * N Tropy model seems to be broken for [specific Jumping animation](https://cdn.discordapp.com/attachments/574619840061374464/1063095299544977509/2023-01-12_20-40-24.mp4).

Seconding this
