### ISSUE TITLE
Extraction crashes at plugin step with the latest psx-modding-toolchain

### ISSUE THREAD

**Issue by DCxDemo** [CTR-tools/CTR-ModSDK#87]
Crash is caused by the missing additional ```version``` param in the self.plugin.extract.
https://github.com/CTR-tools/CTR-ModSDK/blob/main/plugins/plugin.py

the breaking change:
https://github.com/mateusfavarin/psx-modding-toolchain/commit/aebf3ed08a2478f11b2b3bad2b92c72e46f34712

**Comment by Superstarxalien** [comment]
fixed. this took way too long
